# IoT Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-app
  labels:
    io.iot.service: iot-app
spec:
  replicas: 5
  selector:
    matchLabels:
      io.iot.service: iot-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.iot.network/app-network: "true"
        io.iot.service: iot-app
    spec:
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: vultr-cr-credentials
  
      containers:
      - name: gin-app
        # Adjust image as needed
        image: ewr.vultrcr.com/gendoc/uspresearch24:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

        # Non-sensitive environment variables
        envFrom:
        - configMapRef:
            name: iot-env

        # Sensitive secrets from secretKeyRefs, plus POD name
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: iot-db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: iot-db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: iot-db-secret
              key: POSTGRES_DATABASE

        # Add both POD_NAME and NODE_NAME, each from a fieldRef
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

        resources: {}

      restartPolicy: Always