# IoT Application Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iot-app-ingress
  namespace: usp-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # Ensures paths are forwarded correctly
    
    # Load balancing
    # nginx.ingress.kubernetes.io/load-balance: "round_robin"  
    # nginx.ingress.kubernetes.io/load-balance: "least_conn"
    nginx.ingress.kubernetes.io/load-balance: "random"
    
spec:
  ingressClassName: nginx  # Specify the NGINX Ingress Class
  rules:
    - host: iot-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iot-app
                port:
                  number: 8080