# Docker Registry Secret
apiVersion: v1
kind: Secret
metadata:
  name: vultr-cr-credentials
data:
  .dockerconfigjson: eyJhdXRocyI6eyJld3IudnVsdHJjci5jb20iOnsiYXV0aCI6ImNtOWliM1FrWjJWdVpHOWpLMkk0WVdZeE5HRXpMV1EwWlRVdE5EQmlNUzFpTXpZNExUSTFNV1EwTUdSbVlqTm1OVHBTTTI5WFdGQktOR1JCTXpWT2RITllURFZIWVdabFpEa3dWWEpNUlZCblRBPT0ifX19
type: kubernetes.io/dockerconfigjson

---

# ConfigMap for other environment variables (non-sensitive)
apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-env
  labels:
    io.iot.service: iot-env
data:
  ENVIRONMENT: PROD
  GIN_PORT: '8080'
  POSTGRES_HOST: postgres  # Referring to the PostgreSQL service within the cluster
  POSTGRES_PORT: '5432'
  REDIS_ADDRESS: redis:6379