apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
  storageClassName: vultr-block-storage-hdd