
repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts

releases:
- name: grafana
  namespace: monitoring
  chart: grafana/grafana
  values:
  - replicas: 1

    image:
      registry: docker.io
      repository: grafana/grafana
      tag: latest
      pullPolicy: IfNotPresent

      service:
        enabled: true
        type: ClusterIP
        port: 3000
        targetPort: 3000

      storageClass: standard

      serviceAccount:
        create: true

      persistence:
        type: pvc
        enabled: true
        accessModes:
          - ReadWriteOnce
        size: 5Gi
        storageClassName: standard

      ingress:
        enabled: true
        ingressClassName: nginx