apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx-controller-metrics
  namespace: monitoring
  labels:
    # This label must match your Prometheus's serviceMonitorSelector or 
    # serviceMonitorSelectorNilUsesHelmValues = false, so that ALL SMs are discovered
    release: kube-prometheus-stack  
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller
  namespaceSelector:
    matchNames:
      - ingress-nginx
  endpoints:
    - port: metrics           # Must match the name of the port in the metrics Service
      interval: 30s
      path: /metrics